global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'ride-service'
    static_configs:
      - targets: ['ride-service:8081']

  - job_name: 'driver-service'
    static_configs:
      - targets: ['driver-service:8082']

  - job_name: 'passenger-service'
    static_configs:
      - targets: ['passenger-service:8083']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:8080']
